version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/php:cli # ...with this image as the primary container; this is where all `steps` will run
    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      - run: ./vendor/bin/codecept build
      - run: ./vendor/bin/codecept run
